name: Unit tests

on:
  pull_request:
    branches: [master-2.0]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run unit tests
        run: composer test
